# Action to check for spelling errors
name: misspell-fixer-action

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@main
        with:
          token: ${{ secrets.BOT_ACTIONS }}
          commit-message: "fix(typo): ğŸ› typo fixes by misspell-fixer"
          title: "fix(typo): ğŸ› typo fixes by misspell-fixer"
